# Generated by Django 5.2.5 on 2025-08-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_Name', models.CharField(max_length=100)),
                ('product_Category', models.CharField(blank=True, max_length=50, null=True)),
                ('Price_BDT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.PositiveIntegerField()),
                ('Company', models.CharField(blank=True, max_length=50, null=True)),
                ('Stock_Status', models.CharField(blank=True, max_length=20, null=True)),
                ('Discount', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('Author', models.CharField(blank=True, max_length=100, null=True)),
                ('Publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('b_Language', models.CharField(blank=True, max_length=50, null=True)),
                ('b_Pages', models.PositiveIntegerField(blank=True, null=True)),
                ('Genre', models.CharField(blank=True, max_length=50, null=True)),
                ('Review', models.TextField(blank=True, null=True)),
                ('Rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerComponents',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('Component_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Specs', models.TextField(blank=True, null=True)),
                ('Compatibility', models.CharField(blank=True, max_length=100, null=True)),
                ('Warranty', models.CharField(blank=True, max_length=50, null=True)),
                ('Review', models.TextField(blank=True, null=True)),
                ('Rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('Model', models.CharField(blank=True, max_length=50, null=True)),
                ('Warranty', models.CharField(blank=True, max_length=50, null=True)),
                ('Power_Usage', models.CharField(blank=True, max_length=20, null=True)),
                ('Dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('Energy_Rating', models.CharField(blank=True, max_length=10, null=True)),
                ('Review', models.TextField(blank=True, null=True)),
                ('Rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('groc_Review', models.TextField(blank=True, null=True)),
                ('groc_Rate', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('groc_Size', models.CharField(blank=True, max_length=20, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('Exp_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAppliances',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('Power_Usage', models.CharField(blank=True, max_length=20, null=True)),
                ('Dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('Warranty', models.CharField(blank=True, max_length=50, null=True)),
                ('Energy_Rating', models.CharField(blank=True, max_length=10, null=True)),
                ('Review', models.TextField(blank=True, null=True)),
                ('Rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkinCareProducts',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('Ingredients', models.TextField(blank=True, null=True)),
                ('Sc_Size', models.CharField(blank=True, max_length=50, null=True)),
                ('Review', models.TextField(blank=True, null=True)),
                ('Rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationaryProducts',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('Size_Specs', models.CharField(blank=True, max_length=50, null=True)),
                ('Color', models.CharField(blank=True, max_length=30, null=True)),
                ('Material', models.CharField(blank=True, max_length=50, null=True)),
                ('Review', models.TextField(blank=True, null=True)),
                ('Rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bluetooth_Speaker',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.electronics')),
                ('Battery_Capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('Output_Power', models.CharField(blank=True, max_length=50, null=True)),
                ('Connectivity', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.electronics')),
                ('Camera_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('Lens_Specs', models.CharField(blank=True, max_length=100, null=True)),
                ('Battery_Capacity', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop_Desktop',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.electronics')),
                ('Processor', models.CharField(blank=True, max_length=50, null=True)),
                ('RAM', models.CharField(blank=True, max_length=50, null=True)),
                ('Storage', models.CharField(blank=True, max_length=50, null=True)),
                ('Graphics_Card', models.CharField(blank=True, max_length=50, null=True)),
                ('Operating_System', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Powerbank',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.electronics')),
                ('Capacity_mAh', models.CharField(blank=True, max_length=50, null=True)),
                ('Output_Ports', models.CharField(blank=True, max_length=50, null=True)),
                ('Input_Type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone_Tablet',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.electronics')),
                ('OS', models.CharField(blank=True, max_length=50, null=True)),
                ('RAM', models.CharField(blank=True, max_length=50, null=True)),
                ('Storage', models.CharField(blank=True, max_length=50, null=True)),
                ('Camera_Specs', models.CharField(blank=True, max_length=100, null=True)),
                ('Battery_Capacity', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
